### PR TITLE
Fix Windows warnings

### PR DESCRIPTION
**Pull request by oierlauzi**
Adopting the PIMPL idiom in more places to ensure binary compatibility. Also fixing minor warnings

### CODE REVIEW

**Comment by oierlauzi** [comment]
Warnings seem to be solved

**Comment by MartinSalinas98** [comment]
I'd take the opportunity to review the SonaCloud rules involved in this PR.
Check if they should be dismissed in this situation specifically or if they should be disabled entirely.

That way we can make sure to leave a clean PR + reduce work from the SonarCloud issue management task.

**Comment by oierlauzi** [comment]
I'd disable all "since-C++xx" rules and dismiss the other 3 specifically for this situation

**Comment by MartinSalinas98** [comment]
I have updated the rules in SonarCloud, setting a custom "Mission critical C++11" profile, which is the same we had with a few tweaks:
- All "since-c++*" that are above c++1 are disabled
- Following Rule of Zero is mandatory. This should not be a probem since all the code is using smart pointers.

**Comment by oierlauzi** [comment]
With the excuse of re-running SonarCloud, I've added a minor fix

**Comment by oierlauzi** [comment]
In general, I am not using the rule of 0. Instead I'm using the Rule of 5. Maybe there will be lots of warnings related to this.

**Comment by MartinSalinas98** [comment]
> In general, I am not using the rule of 0. Instead I'm using the Rule of 5. Maybe there will be lots of warnings related to this.

Okay, so I then created a new one extending the default profile, called "Sonar Way C++<=11", where I deactivated all the "since-c++*" rules that are above C++11.

Let's run it again and see what issues remain.

**Comment by oierlauzi** [comment]
I'd dismiss the remaining 3 smells

**Comment by oierlauzi** [comment]
They are not useless, but I think they are out of context.

**Review by MartinSalinas98 — APPROVED** [review]
Looks good now

**Pull request merged**
