### PR TITLE
Added test for plugin loader

### PR DESCRIPTION
**Pull request by oierlauzi**
Added test for plugin manager. To do so, several mock plugins have been created.

1. Dummy plugin: Valid plugin
2. Plugin that returns NULL on `xmipp4_get_plugin()`
3. Plugin that does not contain `xmipp4_get_plugin()`
4. Plain text file.

As this is an integration test, separated unitary tests from integration tests. Also added asset management for integration tests

### CODE REVIEW

**Review by MartinSalinas98 — CHANGES_REQUESTED** [review]
There is one accepted issue in SonarCloud. Accepted issues are a way of saying "you are right, but it's good for now, I'll fix them later". Is that what you meant?

On a more important note, ubuntu gcc shows 8 possible memleaks, might need to add a condition to open the log.

**Comment by oierlauzi** [comment]
Yes, the codesmell was correct. I meant that. I will take a look at the memory leak

**Comment by MartinSalinas98** [comment]
> Yes, the codesmell was correct. I meant that. I will take a look at the memory leak

Okay, so that issue can be merged and it gets added to the "clean SonarCloud issues task".
In the meantime, I think it would be a good idea to make the GitHub Action show the log of the tests with memleaks only in case there are any. I'm on it.

**Comment by oierlauzi** [comment]
Seems like a GCC bug: It is not destroying static function variables when unloading a dynamic library. Thus, the "name" of the dummy plugin was leaking. I have made it an static global variable, which seems to behave well with GCC.

**Comment by MartinSalinas98** [comment]
> Seems like a GCC bug: It is not destroying static function variables when unloading a dynamic library. Thus, the "name" of the dummy plugin was leaking. I have made it an static global variable, which seems to behave well with GCC.

Do you know if patches are still being developed for gcc 11? If so, just as a side quest, could be nice to isolate it & report it. On our side, using the global variable would do, but, just to help avoid this issue for anyone else.

**Comment by oierlauzi** [comment]
There are plenty of reports about this when I search the issue in Google. I assume they are aware of it

**Review by MartinSalinas98 — APPROVED** [review]

**Pull request merged**
