### PR TITLE
Re-added half dependency

### PR DESCRIPTION
**Pull request by oierlauzi**
Half was deleted in a previous commit. However it will be useful in host compute. Re-adding it in a more elegant CMake script. Also separating fetch_* code blocks in separate files.

### CODE REVIEW

**Comment by oierlauzi** [comment]
@MartinSalinas98 what is CodeQL?

**Comment by oierlauzi** [comment]
CodeQL is failing because it requires `XMIPP4_CORE_BUILD_HALF` set to `ON`

**Comment by MartinSalinas98** [comment]
CodeQL is a tool integrated with GitHub ([see security tab](https://github.com/gigabit-clowns/xmipp4-core/settings/security_analysis#code_scanning_settings)) that scans the project's code looking for vulnerabilities, and it's supposed to be better than static analysis tools.

CodeQL attempts an autobuild with default params. If that does not work, it requires a .yml file with the appropiate params to build the project.

I'm going to try to set it up in advanced mode, and we'll see if it works and we can keep using it. If not, we can probably disable it.

**Comment by MartinSalinas98** [comment]
Btw, i see some warnings in the cmake configuration step for Ubuntu only:
```
-- Build type: Release
-- Generating install
CMake Warning (dev) at /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:1564 (cmake_parse_arguments):
  The BUILD_COMMAND keyword was followed by an empty string or no value at
  all.  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
  ARG_BUILD_COMMAND variable rather than setting it to an empty string.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)
  /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:2145 (cmake_language)
  /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
  cmake/modules/fetch_half.cmake:[36](https://github.com/gigabit-clowns/xmipp4-core/actions/runs/12013304518/job/33486503352?pr=111#step:4:37) (FetchContent_MakeAvailable)
  CMakeLists.txt:64 (fetch_half)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by oierlauzi** [comment]
> Btw, i see some warnings in the cmake configuration step for Ubuntu only:
> 
> ```
> -- Build type: Release
> -- Generating install
> CMake Warning (dev) at /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:1564 (cmake_parse_arguments):
>   The BUILD_COMMAND keyword was followed by an empty string or no value at
>   all.  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
>   ARG_BUILD_COMMAND variable rather than setting it to an empty string.
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)
>   /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:2145 (cmake_language)
>   /usr/local/share/cmake-3.31/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
>   cmake/modules/fetch_half.cmake:[36](https://github.com/gigabit-clowns/xmipp4-core/actions/runs/12013304518/job/33486503352?pr=111#step:4:37) (FetchContent_MakeAvailable)
>   CMakeLists.txt:64 (fetch_half)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> ```

Let me take a look at it.

**Comment by oierlauzi** [comment]
> CodeQL is a tool integrated with GitHub ([see security tab](https://github.com/gigabit-clowns/xmipp4-core/settings/security_analysis#code_scanning_settings)) that scans the project's code looking for vulnerabilities, and it's supposed to be better than static analysis tools.
> 
> CodeQL attempts an autobuild with default params. If that does not work, it requires a .yml file with the appropiate params to build the project.
> 
> I'm going to try to set it up in advanced mode, and we'll see if it works and we can keep using it. If not, we can probably disable it.

I think it is OK to have it enabled. In the worst case scenario, we can change the default value of the problematic CMakeparameter. This opens another question: There are two variables which handle the behavior of two dependencies: `XMIPP4_CORE_BUILD_SPDLOG` and `XMIPP4_CORE_BUILD_HALF`.  When they are set to `ON` the respective packages are compiled from source together with xmipp4. This makes it easy to compile xmipp4 without installing any external dependecies (which may be needed when the user has no sudo). When the variables are set to `OFF` the respective dependencies are searched in the system. This is also useful when creating packages (e.g. conda) as the dependencies should be installed by the package manager. Should this options be `ON` or `OFF` by default.

**Comment by MartinSalinas98** [comment]
> I think it is OK to have it enabled. In the worst case scenario, we can change the default value of the problematic CMakeparameter. This opens another question: There are two variables which handle the behavior of two dependencies: `XMIPP4_CORE_BUILD_SPDLOG` and `XMIPP4_CORE_BUILD_HALF`. When they are set to `ON` the respective packages are compiled from source together with xmipp4. This makes it easy to compile xmipp4 without installing any external dependecies (which may be needed when the user has no sudo). When the variables are set to `OFF` the respective dependencies are searched in the system. This is also useful when creating packages (e.g. conda) as the dependencies should be installed by the package manager. Should these options be `ON` or `OFF` by default? If set to `ON`, probably we do not need to customize CodeQL

I'd leave them ON by default. It'll simplify most compilation attempts, and, as a byproduct, enables autoscan in CodeQL

**Review by MartinSalinas98 — APPROVED** [review]

**Pull request merged**
