### PR TITLE
Print leaks on actions when they exist

### PR DESCRIPTION
**Pull request by MartinSalinas98**

### CODE REVIEW

**Comment by MartinSalinas98** [comment]
@oierlauzi could you add the code causing the memleak? (so i can try to detect it and print the logs).
I was planning to revert to a commit before it got fixed, but the squash merge denied my plans.

**Comment by MartinSalinas98** [comment]
tee command does not seem to be properly creating the file then running ctest (works with other commands). Will have to replicate this locally

**Comment by MartinSalinas98** [comment]
This already works, what do you think @oierlauzi, would it be useful to have this logs shown dynamically in case of memory leaks & stop the pipeline to make sure no new leaks enter the main branch?

**Comment by oierlauzi** [comment]
What do you mean with "stop the pipeline". I would not merge any code that is leaking.

**Comment by oierlauzi** [comment]
Great! In this way its almost impossible to merge leaky code

**Comment by oierlauzi** [comment]
Maybe could we simplify code instructing valgrind to return a non-zero return code on failure?
https://stackoverflow.com/questions/55321934/how-to-let-cmake-ctest-memcheck-exit-with-status-code-1-on-failure

**Comment by MartinSalinas98** [comment]
> Maybe could we simplify code instructing valgrind to return a non-zero return code on failure? https://stackoverflow.com/questions/55321934/how-to-let-cmake-ctest-memcheck-exit-with-status-code-1-on-failure

There are two issues with that.

1. It's not on valgrind, [it's on ctest](https://stackoverflow.com/questions/55321934/how-to-let-cmake-ctest-memcheck-exit-with-status-code-1-on-failure#comment97378412_55324752).
2. Even if it worked as intended, it would not show the logs of the affected tests, which means the developer would need to reproduce it locally.

**Comment by oierlauzi** [comment]
> > Maybe could we simplify code instructing valgrind to return a non-zero return code on failure? https://stackoverflow.com/questions/55321934/how-to-let-cmake-ctest-memcheck-exit-with-status-code-1-on-failure
> 
> There are two issues with that.
> 
>     1. It's not on valgrind, [it's on ctest](https://stackoverflow.com/questions/55321934/how-to-let-cmake-ctest-memcheck-exit-with-status-code-1-on-failure#comment97378412_55324752).
> 
>     2. Even if it worked as intended, it would not show the logs of the affected tests, which means the developer would need to reproduce it locally.

1. ctest returns 0 because valgrind did.
2. The log of valgrind is not that helpful, in any case local reproducibility with valgrind and gdb would be required to find the root issue.

**Comment by oierlauzi** [comment]
I would merge this code and see later if it can be simplified

**Review by oierlauzi — APPROVED** [review]

**Pull request merged**
